# Generated by Django 2.0.7 on 2020-08-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0002_auto_20200805_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='startedFrom',
            field=models.DateTimeField(verbose_name='Started From'),
        ),
    ]
