# Generated by Django 2.0.7 on 2020-08-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0003_auto_20200805_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcourses',
            name='startedFrom',
        ),
    ]
