# Generated by Django 2.0.7 on 2020-08-05 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0004_remove_allcourses_startedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='startedFrom',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 17, 9, 26, 77849, tzinfo=utc), verbose_name='Started From'),
            preserve_default=False,
        ),
    ]
